### ISSUE TITLE
Besoin de CSS pour liste recettes

### ISSUE THREAD

**Issue by NeverTwice** [Chateux/wordpress-gr5#3]
Hey @adrienpayen ,

J'ai besoin du style (html&css) pour l'affichage widget des 5 meilleurs recettes.

Dans l'idée il faut que ce soit un affichage blocs verticaux comme ceci:
Exemple : (http://2.bp.blogspot.com/-3Ar8aTBfuLE/UZJSNVu8NLI/AAAAAAAAAZY/8ecTMQyP16M/s1600/Flexible+Recent+Posts+Widget+With+Thumbnail.png)

Il me faut dedans :
- Une image de la recette
- Le titre de la recette 
- Un lien read more

Tu peux me mettre le template dans le fichier Objets/BestRecipes et mettre à la place du commentaire "Ajout du template" 

Thanks,

**Comment by Chateux** [comment]
Je vous conseille de copier/coller le lien car il bug lorsqu'on clique dessus.

**Comment by NeverTwice** [comment]
#Updated thanks!

**Comment by Chateux** [comment]
@adrienpayen du coup ça en est où niveau CSS ?
